from . import config

GROUP_TOKEN = config["VK"]["GROUP_TOKEN"]
SOURCE_CONVERSATION_ID = config["VK"]["SOURCE_CONVERSATION_ID"]
# SOURCE_CONVERSATION_ID = config["VK"]["SOURCE_CONVERSATION_ID_STAGING"]
