from . import config

BOT_TOKEN = config["TG"]["BOT_TOKEN"]
DESTINATION_CONVERSATION_ID = config["TG"]["DESTINATION_CONVERSATION_ID"]
# DESTINATION_CONVERSATION_ID = config["TG"]["DESTINATION_CONVERSATION_ID_STAGING"]
